# Generated by Django 3.0.8 on 2020-08-23 05:10

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='users/avatar/default.jpg', upload_to=users.models.re_name),
        ),
    ]
